### ISSUE TITLE
Locate Training/Test Data

### ISSUE THREAD

**Issue by PythonSemicolon** [PythonSemicolon/550FinalProject#8]
For chosen translators/authors. Either in PDF/txt file format, so easily extractable to put into models.

**Comment by PythonSemicolon** [comment]
@AlbertoLopezGarcia you can add the list of translators and works here

**Comment by AlbertoLopezGarcia** [comment]
- Eng -> Spanish: Borges, Jorge Luis
- Eng -> German: Kruger, Lore
- Eng -> Indonesian: Haryono, A
- Eng -> Russian: Rajt-Kovaleva, Rita
- Eng -> Mandarin/Japanese/Korean: Murakami, Haruki
